token:
   path: /token
   controller: App\Controller\UserController::token

# index.html.twig
index_page:
   path: /
   controller: App\Controller\MainController::index

# profile.html.twig
profile_page:
   path: /profile
   controller: App\Controller\UserController::profilePage

# profile.html.twig
user_profile_page:
   path: /profile
   controller: App\Controller\EventController::profile

# shop.html.twig
shop_page:
   path: /shop
   controller: App\Controller\ShopController::index

# shop.new_product.html.twig
shop__new_page:
   path: /shop/products/new
   controller: App\Controller\ShopController::newProductPage

# shop.edit_product.html.twig
shop_edit_page:
   path: /shop/products/edit
   controller: App\Controller\ShopController::editProductPage

# register.html.twig
user_register_page:
   path: /register
   controller: App\Controller\UserController::registerPage

# user.html.twig
user_login_page:
   path: /login
   controller: App\Controller\UserController::loginPage

user_logout:
  path: /users/logout
  controller: App\Controller\UserController::logout

event_get_all:
  path: /events/get/all
  controller: App\Controller\EventController::getEvents

# events.html.twig
event_get_all_page:
  path: /events
  controller: App\Controller\EventController::showAllEventsPage

# event.html.twig
event_show_id_page:
  path: /events/{id}
  controller: App\Controller\EventController::showEventPage

# event_edit.html.twig
event_edit_page:
  path: /events/edit/{id}
  controller: App\Controller\EventController::editEventPage

# event_new.html.twig
event_new_page:
  path: /events/action/new
  controller: App\Controller\EventController::newEventPage

event_delete:
  path: /events/action/delete
  controller: App\Controller\EventController::deleteEvent

event_subscribe:
  path: /events/action/subscribe
  controller: App\Controller\EventController::subscribeEvent

event_unSubscribe:
  path: /events/action/unSubscribe
  controller: App\Controller\EventController::unSubscribeEvent

event_addPicture:
  path: /events/action/addPicture
  controller: App\Controller\EventController::addPicture

event_sendComment:
  path: /events/action/sendcomment
  controller: App\Controller\EventController::sendComment

event_delComment:
  path: /events/action/delcomment
  controller: App\Controller\EventController::delComment

event_delPicture:
  path: /events/action/delPicture
  controller: App\Controller\EventController::delPicture

event_downloadSubscribedStudents:
  path: /events/action/downloadSubscribedStudents
  controller: App\Controller\EventController::downloadSubscribedStudents

event_getAllPictures:
  path: /events/action/getAllPictures
  controller: App\Controller\EventController::getAllPictures

event_subscribeCount:
  path: /events/action/subscribeCount
  controller: App\Controller\EventController::subscribeCount