#index:
#    path: /
#    controller: App\Controller\DefaultController::index

user_login:
  path: /login
  controller: App\Controller\UserController::login

user_logout:
  path: /logout
  controller: App\Controller\UserController::logout