index:
   path: /
   controller: App\Controller\UserController::loginPage

user_login:
  path: /login
  controller: App\Controller\UserController::login

user_logout:
  path: /logout
  controller: App\Controller\UserController::logout