#### MAIN ####

## Pages ##

# index.html.twig
index_page:
   path: /
   controller: App\Controller\MainController::index

legal_page:
  path: /legal
  controller: App\Controller\UserController::legalPage


## Ajax ##

send_mail:
   path: /sendmail
   controller: App\Controller\UserController::sendMailTo



#### USER ####

## Pages ##

# profile.html.twig
profile_page:
   path: /profile
   controller: App\Controller\UserController::profilePage

# profile.preference.html.twig
profile_pref_page:
   path: /profile/preference
   controller: App\Controller\UserController::profilePreferencePage

# register.html.twig
user_register_page:
   path: /register
   controller: App\Controller\UserController::registerPage

# user.html.twig
user_login_page:
   path: /login
   controller: App\Controller\UserController::loginPage

user_admin_page:
  path: /admin
  controller: App\Controller\UserController::adminPage

  
## Ajax ##

user_accept_cookies:
   path: /cookies
   controller: App\Controller\UserController::acceptCookies

user_logout:
  path: /users/logout
  controller: App\Controller\UserController::logout

user_edit_preferences:
  path: /users/preferences/edit
  controller: App\Controller\UserController::editPreferences




#### SHOP ####

## Pages ##

# shop.html.twig
shop_page:
   path: /shop
   controller: App\Controller\ShopController::index

# shop_cart.html.twig
shop_cart_page:
   path: /shop/cart
   controller: App\Controller\ShopController::cartPage

# shop.new_product.html.twig
shop_new_product_page:
   path: /shop/products/new
   controller: App\Controller\ShopController::newProductPage

# shop.edit_product.html.twig
shop_edit_product_page:
   path: /shop/products/edit/{id}
   controller: App\Controller\ShopController::editProductPage

# shop.edit_product.html.twig
shop_edit_page:
   path: /shop/products/edit
   controller: App\Controller\ShopController::editProductPage

# shop.categories.html.twig
shop_categories_page:
   path: /shop/categories
   controller: App\Controller\ShopController::categoriesPage


## Ajax ##

shop_remove_product:
   path: /shop/products/remove
   controller: App\Controller\ShopController::removeProduct

shop_new_category:
   path: /shop/categories/new
   controller: App\Controller\ShopController::newCategory

shop_remove_category:
   path: /shop/categories/remove
   controller: App\Controller\ShopController::removeCategory

shop_add_product_cart:
   path: /shop/products/add
   controller: App\Controller\ShopController::addToCart

shop_remove_product_cart:
   path: /shop/products/removecart
   controller: App\Controller\ShopController::removeFromCart

shop_buy_cart:
  path: /events/cart/buy
  controller: App\Controller\ShopController::buyCart





#### EVENTS ####

## Pages ##

# events.html.twig
event_get_all_page:
  path: /events
  controller: App\Controller\EventController::showAllEventsPage

# event.html.twig
event_show_id_page:
  path: /events/{id}
  controller: App\Controller\EventController::showEventPage

# event_edit.html.twig
event_edit_page:
  path: /events/edit/{id}
  controller: App\Controller\EventController::editEventPage

# event_new.html.twig
event_new_page:
  path: /events/action/new
  controller: App\Controller\EventController::newEventPage


## Ajax ##
event_get_all:
  path: /events/get/all
  controller: App\Controller\EventController::getEvents

event_delete:
  path: /events/action/delete
  controller: App\Controller\EventController::deleteEvent

event_subscribe:
  path: /events/action/subscribe
  controller: App\Controller\EventController::subscribeEvent

event_unSubscribe:
  path: /events/action/unSubscribe
  controller: App\Controller\EventController::unSubscribeEvent

event_addPicture:
  path: /events/action/addPicture
  controller: App\Controller\EventController::addPicture

event_picture_like:
  path: /events/action/like
  controller: App\Controller\EventController::likePicture

event_picture_unlike:
  path: /events/action/unlike
  controller: App\Controller\EventController::unlikePicture

event_picture_getAllLike:
  path: /events/action/getAllLike
  controller: App\Controller\EventController::getAllLike

event_sendComment:
  path: /events/action/sendcomment
  controller: App\Controller\EventController::sendComment

event_delComment:
  path: /events/action/delcomment
  controller: App\Controller\EventController::delComment

event_delPicture:
  path: /events/action/delPicture
  controller: App\Controller\EventController::delPicture

event_downloadSubscribedStudents:
  path: /events/action/downloadSubscribedStudents
  controller: App\Controller\EventController::downloadSubscribedStudents

event_getAllPictures:
  path: /events/action/getAllPictures
  controller: App\Controller\EventController::getAllPictures

event_subscribeCount:
  path: /events/action/subscribeCount
  controller: App\Controller\EventController::subscribeCount

event_getSubscribe:
  path: /events/action/getSubscribe/{id}
  controller: App\Controller\EventController::getSubscribeCSV

event_getPicture:
  path: /events/action/getPictureCSV
  controller: App\Controller\EventController::getPictureCSV
