token:
   path: /token
   controller: App\Controller\UserController::token

# index.html.twig
index_page:
   path: /
   controller: App\Controller\MainController::index

# event.html.twig
event_index_page:
   path: /events
   controller: App\Controller\EventController::index

# profile.html.twig
user_profile_page:
   path: /profile
   controller: App\Controller\EventController::profile

# register.html.twig
user_register_page:
   path: /register
   controller: App\Controller\UserController::registerPage

# user.html.twig
user_login_page:
   path: /login
   controller: App\Controller\UserController::loginPage

user_logout:
  path: /users/logout
  controller: App\Controller\UserController::logout

event_send_comment:
  path: /events/sendcomment
  controller: App\Controller\EventController::sendComment